// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ol_api_dotnet.Data;

#nullable disable

namespace ol_api_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250715065919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ol_api_dotnet.Models.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CampaignActivityActiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CampaignActivityActiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("CampaignActivityAllTimeActive")
                        .HasColumnType("boolean");

                    b.Property<string>("CampaignPhotoMime")
                        .HasColumnType("text");

                    b.Property<string>("CampaignPhotoOriginalName")
                        .HasColumnType("text");

                    b.Property<string>("CampaignPhotoPath")
                        .HasColumnType("text");

                    b.Property<bool?>("CampaignVisibilityAllTimeVisible")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CampaignVisibilityVisibleFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CampaignVisibilityVisibleTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConditionsDescription")
                        .HasColumnType("text");

                    b.Property<decimal>("CostInPoints")
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Coupons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Levels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LimitPerUser")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Reward")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Segments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<bool>("SingleCoupon")
                        .HasColumnType("boolean");

                    b.Property<bool>("Unlimited")
                        .HasColumnType("boolean");

                    b.Property<string>("UsageInstruction")
                        .HasColumnType("text");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("ol_api_dotnet.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ol_api_dotnet.Models.Admin", b =>
                {
                    b.HasBaseType("ol_api_dotnet.Models.User");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<bool>("External")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Admin");
                });
#pragma warning restore 612, 618
        }
    }
}
